# Generated by Django 5.1.1 on 2024-09-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('types', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('yearofrelease', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('salary', models.IntegerField(default=1)),
                ('graphic_of_work', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Readers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50)),
                ('readers_ticket', models.CharField(max_length=8)),
                ('book_in_use', models.BooleanField()),
                ('debt', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Graphic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=50)),
                ('Hours_Of_Work', models.IntegerField(default=1)),
                ('Personnelity', models.ManyToManyField(to='main.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Have', models.BooleanField()),
                ('Book', models.ManyToManyField(to='main.books')),
                ('Reader', models.ManyToManyField(to='main.readers')),
            ],
        ),
    ]
