# Generated by Django 5.1.1 on 2024-09-23 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
        migrations.RemoveField(
            model_name='books',
            name='price',
        ),
        migrations.RemoveField(
            model_name='books',
            name='types',
        ),
        migrations.RemoveField(
            model_name='books',
            name='yearofrelease',
        ),
        migrations.AddField(
            model_name='books',
            name='birthday',
            field=models.DateField(default=datetime.datetime(1999, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
