# Generated by Django 5.1.1 on 2024-09-23 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_books_author_remove_books_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='books',
            name='birthday',
        ),
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='books',
            name='types',
            field=models.CharField(default=datetime.datetime(1999, 1, 1, 0, 0), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='yearofrelease',
            field=models.CharField(default=datetime.datetime(1999, 1, 1, 0, 0), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(to='main.author'),
        ),
    ]
